# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b631b52609586c36aeb49a58f9449ab0c6bee874d73da7948004cbfb6e2671990e21cee626924245ca3cc75779e6385296b6f80e9ef2a5f8972921f6ce2b3f

test:
  secret_key_base: db7a2566c5436af8db5d6fd7430eb9b8017b6bfd6288be053ccadbce4e7c38828d32ee7306fb7435854214190ab9243ce8fce36cf9ae36c02c8f571571a87844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
